sudo: false
language: android
env:
  - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - ./.ci/wait_for_emulator
  - adb shell input keyevent 82 &
script: ./gradlew connectedAndroidTest

android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - android-19
    - sys-img-armeabi-v7a-android-19
    - android-16
    - sys-img-armeabi-v7a-android-16

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a07ed1814913d3265923
