# Site settings
title: MobiLed
description: > # this means to ignore newlines until "baseurl:"
  MobiLed is an application to control your LED lighting system from your
  Android phone or tablet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mobi-led.github.io/mobi-led" # the base hostname & protocol for your site
github_username:  mobi-led

# Build settings
markdown: kramdown
